import type { Book, Manga, Chapter } from '@/types';

export const mockBooks: Book[] = [
  {
    _id: '1',
    title: 'Cien Años de Soledad',
    author: 'Gabriel García Márquez',
    description: 'La novela narra la historia de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo. Es una obra maestra del realismo mágico que explora temas como la soledad, el amor, la guerra y el destino.',
    genre: 'Realismo Magico',
    coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
    pdfUrl: '',
    createdBy: { name: 'Admin' },
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    _id: '2',
    title: '1984',
    author: 'George Orwell',
    description: 'Una distopía clásica que presenta un régimen totalitarian liderado por el Gran Hermano. Winston Smith se rebela contra un sistema que controla cada aspecto de la vida de los ciudadanos, incluyendo sus pensamientos.',
    genre: 'Ciencia Ficcion',
    coverUrl: 'https://images.unsplash.com/photo-1535905557558-afc4877a26fc?w=400&h=600&fit=crop',
    pdfUrl: '',
    createdBy: { name: 'Admin' },
    createdAt: '2024-02-20T10:00:00Z',
  },
  {
    _id: '3',
    title: 'El Principito',
    author: 'Antoine de Saint-Exupéry',
    description: 'Un piloto averiado en el desierto del Sahara se encuentra con un pequeño príncipe proveniente de un asteroide. A través de sus conversaciones, el libro explora temas como la amistad, el amor y la esencia de la vida.',
    genre: 'Fabulas',
    coverUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop',
    pdfUrl: '',
    createdBy: { name: 'Admin' },
    createdAt: '2024-03-10T10:00:00Z',
  },
  {
    _id: '4',
    title: 'Don Quijote de la Mancha',
    author: 'Miguel de Cervantes',
    description: 'La historia del caballero andante más famoso de la literatura universal. Don Quijote, enloquecido por la lectura de libros de caballerías, sale al mundo a combatir el mal y defender a los desfavorecidos, acompañado de su fiel escudero Sancho Panza.',
    genre: 'Clasicos',
    coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
    pdfUrl: '',
    createdBy: { name: 'Admin' },
    createdAt: '2024-04-05T10:00:00Z',
  },
  {
    _id: '5',
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    description: 'En un futuro distópico, los bomberos no apagan incendios, sino que queman libros. Guy Montag, un bombero, comienza a cuestionar su trabajo después de conocer a una joven que desafía el sistema.',
    genre: 'Ciencia Ficcion',
    coverUrl: 'https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=400&h=600&fit=crop',
    pdfUrl: '',
    createdBy: { name: 'Admin' },
    createdAt: '2024-05-12T10:00:00Z',
  },
  {
    _id: '6',
    title: 'La Sombra del Viento',
    author: 'Carlos Ruiz Zafón',
    description: 'En la Barcelona de la posguerra, un joven llamado Daniel descubre un libro que cambiará su vida. Mientras investiga la misteriosa desaparición del autor, se adentra en un mundo de secretos, traiciones y pasiones ocultas.',
    genre: 'Misterio',
    coverUrl: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400&h=600&fit=crop',
    pdfUrl: '',
    createdBy: { name: 'Admin' },
    createdAt: '2024-06-18T10:00:00Z',
  },
];

export const mockMangas: Manga[] = [
  {
    _id: '101',
    title: 'One Piece',
    author: 'Eiichiro Oda',
    description: 'Monkey D. Luffy y su tripulación de piratas navegan por el Grand Line en busca del tesoro más grande del mundo, conocido como "One Piece", para convertirse en el próximo Rey de los Piratas.',
    genre: 'Aventura',
    coverUrl: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=400&h=600&fit=crop',
    createdBy: { name: 'Admin' },
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    _id: '102',
    title: 'Attack on Titan',
    author: 'Hajime Isayama',
    description: 'La humanidad vive dentro de ciudades rodeadas por enormes muros que los protegen de los Titanes. Eren Yeager jura exterminar a todos los Titanes después de presenciar la destrucción de su ciudad.',
    genre: 'Accion',
    coverUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=600&fit=crop',
    createdBy: { name: 'Admin' },
    createdAt: '2024-02-15T10:00:00Z',
  },
  {
    _id: '103',
    title: 'Demon Slayer',
    author: 'Koyoharu Gotouge',
    description: 'Tanjiro Kamado se convierte en un cazador de demonios después de que su familia es masacrada y su hermana Nezuko es convertida en demonio. Busca una cura para devolverle su humanidad.',
    genre: 'Accion',
    coverUrl: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400&h=600&fit=crop',
    createdBy: { name: 'Admin' },
    createdAt: '2024-03-20T10:00:00Z',
  },
  {
    _id: '104',
    title: 'My Hero Academia',
    author: 'Kohei Horikoshi',
    description: 'En un mundo donde casi todos tienen superpoderes llamados "quirks", Izuku Midoriya nace sin ninguno. Sin embargo, su sueño de convertirse en héroe se hace realidad cuando conoce al héroe número uno.',
    genre: 'Superheroes',
    coverUrl: 'https://images.unsplash.com/photo-1607604276583-eef5a0ad8e31?w=400&h=600&fit=crop',
    createdBy: { name: 'Admin' },
    createdAt: '2024-04-25T10:00:00Z',
  },
];

export const mockChapters: Chapter[] = [
  { _id: '1001', mangaId: '101', chapterTitle: 'Romance Dawn', chapterNumber: 1, fileUrl: '', createdAt: '2024-01-10T10:00:00Z' },
  { _id: '1002', mangaId: '101', chapterTitle: 'Luffy vs. Alvida', chapterNumber: 2, fileUrl: '', createdAt: '2024-01-17T10:00:00Z' },
  { _id: '1003', mangaId: '101', chapterTitle: 'El Cazador de Piratas Zoro', chapterNumber: 3, fileUrl: '', createdAt: '2024-01-24T10:00:00Z' },
  { _id: '1004', mangaId: '101', chapterTitle: 'El Gran Capitan Morgan', chapterNumber: 4, fileUrl: '', createdAt: '2024-01-31T10:00:00Z' },
  { _id: '1005', mangaId: '101', chapterTitle: 'El Señor del Hogar', chapterNumber: 5, fileUrl: '', createdAt: '2024-02-07T10:00:00Z' },
  { _id: '2001', mangaId: '102', chapterTitle: 'A Ti, 2000 Años en el Futuro', chapterNumber: 1, fileUrl: '', createdAt: '2024-02-15T10:00:00Z' },
  { _id: '2002', mangaId: '102', chapterTitle: 'Ese Dia', chapterNumber: 2, fileUrl: '', createdAt: '2024-02-22T10:00:00Z' },
  { _id: '2003', mangaId: '102', chapterTitle: 'La Noche de la Graduacion', chapterNumber: 3, fileUrl: '', createdAt: '2024-03-01T10:00:00Z' },
  { _id: '3001', mangaId: '103', chapterTitle: 'Crueldad', chapterNumber: 1, fileUrl: '', createdAt: '2024-03-20T10:00:00Z' },
  { _id: '3002', mangaId: '103', chapterTitle: 'El Extraño', chapterNumber: 2, fileUrl: '', createdAt: '2024-03-27T10:00:00Z' },
  { _id: '3003', mangaId: '103', chapterTitle: 'Regreso a Casa', chapterNumber: 3, fileUrl: '', createdAt: '2024-04-03T10:00:00Z' },
  { _id: '4001', mangaId: '104', chapterTitle: 'Izuku Midoriya: Origen', chapterNumber: 1, fileUrl: '', createdAt: '2024-04-25T10:00:00Z' },
  { _id: '4002', mangaId: '104', chapterTitle: 'Lo Que Hace Un Heroe', chapterNumber: 2, fileUrl: '', createdAt: '2024-05-02T10:00:00Z' },
  { _id: '4003', mangaId: '104', chapterTitle: 'Al AULA!', chapterNumber: 3, fileUrl: '', createdAt: '2024-05-09T10:00:00Z' },
];
